"""add_futsal_and_payout_models

Revision ID: 2e18f9b31356
Revises: 012cc4845c3b
Create Date: 2026-03-02 09:20:18.966327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e18f9b31356'
down_revision: Union[str, Sequence[str], None] = '012cc4845c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('futsal_grounds',
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.AutoString(length=1000), nullable=True),
    sa.Column('ground_type', sa.Enum('INDOOR', 'OUTDOOR', 'HYBRID', name='groundtype'), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('weekend_price_per_hour', sa.Float(), nullable=True),
    sa.Column('peak_hours_start', sa.Time(), nullable=True),
    sa.Column('peak_hours_end', sa.Time(), nullable=True),
    sa.Column('peak_price_multiplier', sa.Float(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('futsal_grounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_futsal_grounds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_futsal_grounds_slug'), ['slug'], unique=True)

    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_redeemed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.AutoString(length=2000), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'PAYMENT', 'AUTH', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('notificationpreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_endpoint', sqlmodel.AutoString(length=2048), nullable=True),
    sa.Column('push_p256dh', sqlmodel.AutoString(length=512), nullable=True),
    sa.Column('push_auth', sqlmodel.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationpreference_user_id'), ['user_id'], unique=True)

    op.create_table('owner_payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'BANK_TRANSFER', name='gatewayprovider'), nullable=False),
    sa.Column('credentials_encrypted', sqlmodel.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.AutoString(length=150), nullable=False),
    sa.Column('account_number_hint', sqlmodel.AutoString(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_payment_gateways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_payment_gateways_owner_id'), ['owner_id'], unique=True)

    op.create_table('payment_transactions',
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', name='paymentprovider'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INITIATED', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('purchase_order_id', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('purchase_order_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('provider_pidx', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('return_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('website_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sqlmodel.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_pidx'), ['provider_pidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_transaction_id'), ['provider_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_type', sa.Enum('WEEKLY', 'MONTHLY', name='recurringtype'), nullable=True),
    sa.Column('recurring_end_date', sa.Date(), nullable=True),
    sa.Column('team_name', sqlmodel.AutoString(length=100), nullable=True),
    sa.Column('notes', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.AutoString(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('qr_code', sqlmodel.AutoString(), nullable=False),
    sa.Column('qr_used', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('favourite_grounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ground_id', name='uq_favourite')
    )
    with op.batch_alter_table('favourite_grounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_grounds_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_grounds_user_id'), ['user_id'], unique=False)

    op.create_table('ground_closures',
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.AutoString(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ground_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ground_closures_ground_id'), ['ground_id'], unique=False)

    op.create_table('ground_images',
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ground_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ground_images_ground_id'), ['ground_id'], unique=False)

    op.create_table('payment_webhooks',
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', name='paymentprovider'), nullable=False),
    sa.Column('event_type', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sqlmodel.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'ON_HOLD', name='payoutstatus'), nullable=False),
    sa.Column('provider', sqlmodel.AutoString(length=50), nullable=True),
    sa.Column('transaction_ref', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_records_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_records_owner_id'), ['owner_id'], unique=False)

    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entries_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_user_id'), ['user_id'], unique=False)

    op.create_table('booking_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('locked_by_booking_id', sa.Integer(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['locked_by_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ground_id', 'booking_date', 'start_time', 'end_time', name='uq_booking_lock_slot')
    )
    with op.batch_alter_table('booking_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_locks_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_locks_ground_id'), ['ground_id'], unique=False)

    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('EARNED', 'REDEEMED', 'EXPIRED', 'BONUS', 'REFUNDED', name='loyaltytransactiontype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_account_id'), ['account_id'], unique=False)

    op.create_table('payout_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payout_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_ledger_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_ledger_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_ledger_settled'), ['settled'], unique=False)

    op.create_table('reviews',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.AutoString(length=1000), nullable=True),
    sa.Column('image_url', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_reply', sqlmodel.AutoString(length=1000), nullable=True),
    sa.Column('owner_replied_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('user_id', 'ground_id', 'booking_id', name='uq_review_booking')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('ipaccesscontrol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipaccesscontrol_ip_address'))

    op.drop_table('ipaccesscontrol')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipaccesscontrol',
    sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False),
    sa.Column('status', sa.VARCHAR(length=11), nullable=False),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=False),
    sa.Column('last_seen', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ipaccesscontrol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipaccesscontrol_ip_address'), ['ip_address'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_ground_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_ledger_settled'))
        batch_op.drop_index(batch_op.f('ix_payout_ledger_owner_id'))
        batch_op.drop_index(batch_op.f('ix_payout_ledger_ground_id'))

    op.drop_table('payout_ledger')
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_account_id'))

    op.drop_table('loyalty_transactions')
    with op.batch_alter_table('booking_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_locks_ground_id'))
        batch_op.drop_index(batch_op.f('ix_booking_locks_booking_date'))

    op.drop_table('booking_locks')
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_ground_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_booking_date'))

    op.drop_table('waitlist_entries')
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_records_owner_id'))
        batch_op.drop_index(batch_op.f('ix_payout_records_ground_id'))

    op.drop_table('payout_records')
    op.drop_table('payment_webhooks')
    with op.batch_alter_table('ground_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ground_images_ground_id'))

    op.drop_table('ground_images')
    with op.batch_alter_table('ground_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ground_closures_ground_id'))

    op.drop_table('ground_closures')
    with op.batch_alter_table('favourite_grounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_grounds_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_grounds_ground_id'))

    op.drop_table('favourite_grounds')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_qr_code'))
        batch_op.drop_index(batch_op.f('ix_bookings_ground_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_date'))

    op.drop_table('bookings')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_pidx'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('owner_payment_gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_payment_gateways_owner_id'))

    op.drop_table('owner_payment_gateways')
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationpreference_user_id'))

    op.drop_table('notificationpreference')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_user_id'))

    op.drop_table('loyalty_accounts')
    with op.batch_alter_table('futsal_grounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_futsal_grounds_slug'))
        batch_op.drop_index(batch_op.f('ix_futsal_grounds_owner_id'))

    op.drop_table('futsal_grounds')
    # ### end Alembic commands ###
