"""add_domain_to_userrole_and_scope_to_permission

Revision ID: 357807d55b37
Revises: be34b1195d01
Create Date: 2026-03-03 13:48:27.290666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '357807d55b37'
down_revision: Union[str, Sequence[str], None] = 'be34b1195d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ground_id', sa.Integer(), nullable=True))
        batch_op.alter_column('resource',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Enum('grounds', 'bookings', 'reviews', 'users', 'staff', 'payments', 'reports', 'settings', 'subscriptions', 'payouts', name='resourceenum'),
               existing_nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('read', 'write', 'update', 'delete', 'manage', name='actionenum'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_permission_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_ground_id'), ['ground_id'], unique=False)
        batch_op.create_foreign_key('fk_permission_created_by_id_user', 'user', ['created_by_id'], ['id'])
        batch_op.create_foreign_key('fk_permission_ground_id_futsal_grounds', 'futsal_grounds', ['ground_id'], ['id'])

    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sqlmodel.AutoString(length=100), nullable=False, server_default='global'))
        batch_op.create_index(batch_op.f('ix_userrole_domain'), ['domain'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userrole_domain'))
        batch_op.drop_column('domain')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_constraint('fk_permission_created_by_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_permission_ground_id_futsal_grounds', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_permission_ground_id'))
        batch_op.drop_index(batch_op.f('ix_permission_created_by_id'))
        batch_op.alter_column('action',
               existing_type=sa.Enum('read', 'write', 'update', 'delete', 'manage', name='actionenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('resource',
               existing_type=sa.Enum('grounds', 'bookings', 'reviews', 'users', 'staff', 'payments', 'reports', 'settings', 'subscriptions', 'payouts', name='resourceenum'),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('ground_id')
        batch_op.drop_column('created_by_id')

    # ### end Alembic commands ###
