"""init

Revision ID: af761f0254f1
Revises: 
Create Date: 2026-03-10 15:25:17.457294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af761f0254f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('v0', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v1', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v2', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v3', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v4', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v5', sqlmodel.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casbin_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casbin_rule_ptype'), ['ptype'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v0'), ['v0'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v1'), ['v1'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v2'), ['v2'], unique=False)

    op.create_table('role',
    sa.Column('name', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_quarterly', sa.Float(), nullable=True),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('max_grounds', sa.Integer(), nullable=False),
    sa.Column('max_staff', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('features', sqlmodel.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('username', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('email', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('otp_enabled', sa.Boolean(), nullable=False),
    sa.Column('otp_verified', sa.Boolean(), nullable=False),
    sa.Column('otp_base32', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('otp_auth_url', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('social_provider', sqlmodel.AutoString(length=50), nullable=True),
    sa.Column('social_id', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_social_id'), ['social_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_social_provider'), ['social_provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('fcmdevicetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fcm_token', sqlmodel.AutoString(length=512), nullable=False),
    sa.Column('device_type', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('device_name', sqlmodel.AutoString(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fcmdevicetoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fcmdevicetoken_fcm_token'), ['fcm_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_fcmdevicetoken_user_id'), ['user_id'], unique=False)

    op.create_table('futsal_grounds',
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=120), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('location', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.AutoString(length=1000), nullable=True),
    sa.Column('ground_type', sa.Enum('INDOOR', 'OUTDOOR', 'HYBRID', name='groundtype'), nullable=False),
    sa.Column('price_per_hour', sa.Float(), nullable=False),
    sa.Column('weekend_price_per_hour', sa.Float(), nullable=True),
    sa.Column('peak_hours_start', sa.Time(), nullable=True),
    sa.Column('peak_hours_end', sa.Time(), nullable=True),
    sa.Column('peak_price_multiplier', sa.Float(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_by_limit', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('futsal_grounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_futsal_grounds_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_futsal_grounds_slug'), ['slug'], unique=True)

    op.create_table('loginattempt',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=False),
    sa.Column('user_agent', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loyalty_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('points_balance', sa.Integer(), nullable=False),
    sa.Column('total_earned', sa.Integer(), nullable=False),
    sa.Column('total_redeemed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_accounts_user_id'), ['user_id'], unique=True)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('body', sqlmodel.AutoString(length=2000), nullable=False),
    sa.Column('type', sa.Enum('INFO', 'SUCCESS', 'WARNING', 'ERROR', 'PAYMENT', 'AUTH', 'SYSTEM', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('notificationpreference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('websocket_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_endpoint', sqlmodel.AutoString(length=2048), nullable=True),
    sa.Column('push_p256dh', sqlmodel.AutoString(length=512), nullable=True),
    sa.Column('push_auth', sqlmodel.AutoString(length=256), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificationpreference_user_id'), ['user_id'], unique=True)

    op.create_table('owner_payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'BANK_TRANSFER', name='gatewayprovider'), nullable=False),
    sa.Column('credentials_encrypted', sqlmodel.AutoString(), nullable=False),
    sa.Column('account_name', sqlmodel.AutoString(length=150), nullable=False),
    sa.Column('account_number_hint', sqlmodel.AutoString(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_payment_gateways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_payment_gateways_owner_id'), ['owner_id'], unique=True)

    op.create_table('payment_transactions',
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', name='paymentprovider'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'INITIATED', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('purchase_order_id', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('purchase_order_name', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('provider_transaction_id', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('provider_pidx', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('return_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('website_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', sqlmodel.AutoString(), nullable=True),
    sa.Column('failure_reason', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_pidx'), ['provider_pidx'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_provider_transaction_id'), ['provider_transaction_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transactions_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('tenant',
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=63), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_slug'), ['slug'], unique=True)

    op.create_table('tokentracking',
    sa.Column('token_jti', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('token_type', sa.Enum('access', 'refresh', 'password_reset', 'email_verification', 'temp_auth', 'bearer', name='tokentype'), nullable=True),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=False),
    sa.Column('user_agent', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokentracking_token_jti'), ['token_jti'], unique=True)

    op.create_table('usedtoken',
    sa.Column('token_jti', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('token_purpose', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usedtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usedtoken_token_jti'), ['token_jti'], unique=True)

    op.create_table('userprofile',
    sa.Column('first_name', sqlmodel.AutoString(length=40), nullable=False),
    sa.Column('last_name', sqlmodel.AutoString(length=40), nullable=False),
    sa.Column('phone', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('image_url', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('bio', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('domain', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userrole_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_userrole_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userrole_user_id'), ['user_id'], unique=False)

    op.create_table('bookings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('paid_amount', sa.Float(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurring_type', sa.Enum('WEEKLY', 'MONTHLY', name='recurringtype'), nullable=True),
    sa.Column('recurring_end_date', sa.Date(), nullable=True),
    sa.Column('team_name', sqlmodel.AutoString(length=100), nullable=True),
    sa.Column('notes', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('cancellation_reason', sqlmodel.AutoString(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='bookingstatus'), nullable=False),
    sa.Column('qr_code', sqlmodel.AutoString(), nullable=False),
    sa.Column('qr_used', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('pre_play_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_qr_code'), ['qr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('favourite_grounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ground_id', name='uq_favourite')
    )
    with op.batch_alter_table('favourite_grounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favourite_grounds_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favourite_grounds_user_id'), ['user_id'], unique=False)

    op.create_table('ground_closures',
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sqlmodel.AutoString(length=300), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ground_closures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ground_closures_ground_id'), ['ground_id'], unique=False)

    op.create_table('ground_images',
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ground_images', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ground_images_ground_id'), ['ground_id'], unique=False)

    op.create_table('ground_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'STAFF', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('disabled_by_limit', sa.Boolean(), nullable=False),
    sa.Column('invite_token', sqlmodel.AutoString(length=64), nullable=True),
    sa.Column('invite_email', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ground_id', 'user_id', name='uq_ground_staff')
    )
    with op.batch_alter_table('ground_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ground_staff_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ground_staff_invite_token'), ['invite_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_ground_staff_user_id'), ['user_id'], unique=False)

    op.create_table('owner_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'GRACE', 'EXPIRED', 'CANCELLED', 'PAST_DUE', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('last_payment_transaction_id', sa.Integer(), nullable=True),
    sa.Column('billing_interval', sqlmodel.AutoString(), nullable=False),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_payment_transaction_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_subscriptions_owner_id'), ['owner_id'], unique=True)

    op.create_table('payment_webhooks',
    sa.Column('provider', sa.Enum('KHALTI', 'ESEWA', 'STRIPE', 'PAYPAL', name='paymentprovider'), nullable=False),
    sa.Column('event_type', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('raw_payload', sqlmodel.AutoString(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payout_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('currency', sqlmodel.AutoString(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'ON_HOLD', name='payoutstatus'), nullable=False),
    sa.Column('payout_mode', sqlmodel.AutoString(length=10), nullable=False),
    sa.Column('provider', sqlmodel.AutoString(length=50), nullable=True),
    sa.Column('transaction_ref', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('initiated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_records_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_records_owner_id'), ['owner_id'], unique=False)

    op.create_table('permission',
    sa.Column('resource', sa.Enum('grounds', 'bookings', 'reviews', 'users', 'staff', 'payments', 'reports', 'settings', 'subscriptions', 'payouts', name='resourceenum'), nullable=False),
    sa.Column('action', sa.Enum('read', 'write', 'update', 'delete', 'manage', name='actionenum'), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('ground_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_resource'), ['resource'], unique=False)

    op.create_table('tenantinvitation',
    sa.Column('email', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='tenantrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('token', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenantinvitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenantinvitation_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantinvitation_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantinvitation_token'), ['token'], unique=True)

    op.create_table('tenantmember',
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='tenantrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenantmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenantmember_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantmember_user_id'), ['user_id'], unique=False)

    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entries_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_user_id'), ['user_id'], unique=False)

    op.create_table('booking_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('locked_by_booking_id', sa.Integer(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['locked_by_booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_locks', schema=None) as batch_op:
        batch_op.create_index('ix_booking_lock_ground_date', ['ground_id', 'booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_locks_booking_date'), ['booking_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_locks_ground_id'), ['ground_id'], unique=False)

    op.create_table('loyalty_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.Enum('EARNED', 'REDEEMED', 'EXPIRED', 'BONUS', 'REFUNDED', name='loyaltytransactiontype'), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['loyalty_accounts.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loyalty_transactions_account_id'), ['account_id'], unique=False)

    op.create_table('payout_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Float(), nullable=False),
    sa.Column('platform_fee_pct', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('net_amount', sa.Float(), nullable=False),
    sa.Column('payout_mode', sqlmodel.AutoString(length=10), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payout_records.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_payout_ledger_booking_id')
    )
    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_ledger_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_ledger_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_ledger_settled'), ['settled'], unique=False)

    op.create_table('reviews',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.AutoString(length=1000), nullable=True),
    sa.Column('image_url', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_reply', sqlmodel.AutoString(length=1000), nullable=True),
    sa.Column('owner_replied_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_review_booking_id'),
    sa.UniqueConstraint('user_id', 'ground_id', 'booking_id', name='uq_review_booking')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('rolepermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rolepermission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rolepermission_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rolepermission_role_id'), ['role_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rolepermission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rolepermission_role_id'))
        batch_op.drop_index(batch_op.f('ix_rolepermission_permission_id'))

    op.drop_table('rolepermission')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_ground_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_ledger_settled'))
        batch_op.drop_index(batch_op.f('ix_payout_ledger_owner_id'))
        batch_op.drop_index(batch_op.f('ix_payout_ledger_ground_id'))

    op.drop_table('payout_ledger')
    with op.batch_alter_table('loyalty_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_transactions_account_id'))

    op.drop_table('loyalty_transactions')
    with op.batch_alter_table('booking_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_locks_ground_id'))
        batch_op.drop_index(batch_op.f('ix_booking_locks_booking_date'))
        batch_op.drop_index('ix_booking_lock_ground_date')

    op.drop_table('booking_locks')
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_ground_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_booking_date'))

    op.drop_table('waitlist_entries')
    with op.batch_alter_table('tenantmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenantmember_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenantmember_tenant_id'))

    op.drop_table('tenantmember')
    with op.batch_alter_table('tenantinvitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenantinvitation_token'))
        batch_op.drop_index(batch_op.f('ix_tenantinvitation_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenantinvitation_email'))

    op.drop_table('tenantinvitation')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_resource'))
        batch_op.drop_index(batch_op.f('ix_permission_ground_id'))
        batch_op.drop_index(batch_op.f('ix_permission_created_by_id'))
        batch_op.drop_index(batch_op.f('ix_permission_action'))

    op.drop_table('permission')
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_records_owner_id'))
        batch_op.drop_index(batch_op.f('ix_payout_records_ground_id'))

    op.drop_table('payout_records')
    op.drop_table('payment_webhooks')
    with op.batch_alter_table('owner_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_subscriptions_owner_id'))

    op.drop_table('owner_subscriptions')
    with op.batch_alter_table('ground_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ground_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_ground_staff_invite_token'))
        batch_op.drop_index(batch_op.f('ix_ground_staff_ground_id'))

    op.drop_table('ground_staff')
    with op.batch_alter_table('ground_images', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ground_images_ground_id'))

    op.drop_table('ground_images')
    with op.batch_alter_table('ground_closures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ground_closures_ground_id'))

    op.drop_table('ground_closures')
    with op.batch_alter_table('favourite_grounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favourite_grounds_user_id'))
        batch_op.drop_index(batch_op.f('ix_favourite_grounds_ground_id'))

    op.drop_table('favourite_grounds')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_qr_code'))
        batch_op.drop_index(batch_op.f('ix_bookings_ground_id'))
        batch_op.drop_index(batch_op.f('ix_bookings_booking_date'))

    op.drop_table('bookings')
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userrole_user_id'))
        batch_op.drop_index(batch_op.f('ix_userrole_role_id'))
        batch_op.drop_index(batch_op.f('ix_userrole_domain'))

    op.drop_table('userrole')
    op.drop_table('userprofile')
    with op.batch_alter_table('usedtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usedtoken_token_jti'))

    op.drop_table('usedtoken')
    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokentracking_token_jti'))

    op.drop_table('tokentracking')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_slug'))

    op.drop_table('tenant')
    with op.batch_alter_table('payment_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transactions_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_transaction_id'))
        batch_op.drop_index(batch_op.f('ix_payment_transactions_provider_pidx'))

    op.drop_table('payment_transactions')
    with op.batch_alter_table('owner_payment_gateways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_payment_gateways_owner_id'))

    op.drop_table('owner_payment_gateways')
    with op.batch_alter_table('notificationpreference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificationpreference_user_id'))

    op.drop_table('notificationpreference')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('loyalty_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loyalty_accounts_user_id'))

    op.drop_table('loyalty_accounts')
    op.drop_table('loginattempt')
    with op.batch_alter_table('futsal_grounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_futsal_grounds_slug'))
        batch_op.drop_index(batch_op.f('ix_futsal_grounds_owner_id'))

    op.drop_table('futsal_grounds')
    with op.batch_alter_table('fcmdevicetoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fcmdevicetoken_user_id'))
        batch_op.drop_index(batch_op.f('ix_fcmdevicetoken_fcm_token'))

    op.drop_table('fcmdevicetoken')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_social_provider'))
        batch_op.drop_index(batch_op.f('ix_user_social_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_slug'))

    op.drop_table('subscription_plans')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    with op.batch_alter_table('casbin_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v2'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v1'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v0'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_ptype'))

    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
