"""add_disabled_by_limit_to_grounds_and_staff

Revision ID: b2253e3d70c6
Revises: a1b2c3d4e5f6
Create Date: 2026-03-03 18:48:19.915211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b2253e3d70c6'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('futsal_grounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_by_limit', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('ground_staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disabled_by_limit', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_payout_ledger_booking_id', ['booking_id'])

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_review_booking_id', ['booking_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('uq_review_booking_id', type_='unique')

    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payout_ledger_booking_id', type_='unique')

    with op.batch_alter_table('ground_staff', schema=None) as batch_op:
        batch_op.drop_column('disabled_by_limit')

    with op.batch_alter_table('futsal_grounds', schema=None) as batch_op:
        batch_op.drop_column('disabled_by_limit')

    # ### end Alembic commands ###
