"""add_payout_mode_to_ledger_and_record

Revision ID: be34b1195d01
Revises: fdb0b23f12d4
Create Date: 2026-03-02 09:37:24.774620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'be34b1195d01'
down_revision: Union[str, Sequence[str], None] = 'fdb0b23f12d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_mode', sqlmodel.AutoString(length=10), nullable=False))

    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_mode', sqlmodel.AutoString(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payout_records', schema=None) as batch_op:
        batch_op.drop_column('payout_mode')

    with op.batch_alter_table('payout_ledger', schema=None) as batch_op:
        batch_op.drop_column('payout_mode')

    # ### end Alembic commands ###
