"""add_subscription_and_ground_staff

Revision ID: fdb0b23f12d4
Revises: 2e18f9b31356
Create Date: 2026-03-02 09:31:17.493780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdb0b23f12d4'
down_revision: Union[str, Sequence[str], None] = '2e18f9b31356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=500), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('max_grounds', sa.Integer(), nullable=False),
    sa.Column('max_staff', sa.Integer(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('features', sqlmodel.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_slug'), ['slug'], unique=True)

    op.create_table('ground_staff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ground_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'STAFF', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invite_token', sqlmodel.AutoString(length=64), nullable=True),
    sa.Column('invite_email', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ground_id'], ['futsal_grounds.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ground_id', 'user_id', name='uq_ground_staff')
    )
    with op.batch_alter_table('ground_staff', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ground_staff_ground_id'), ['ground_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ground_staff_invite_token'), ['invite_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_ground_staff_user_id'), ['user_id'], unique=False)

    op.create_table('owner_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'GRACE', 'EXPIRED', 'CANCELLED', 'PAST_DUE', name='subscriptionstatus'), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.Date(), nullable=True),
    sa.Column('current_period_end', sa.Date(), nullable=True),
    sa.Column('last_payment_transaction_id', sa.Integer(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_payment_transaction_id'], ['payment_transactions.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('owner_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_owner_subscriptions_owner_id'), ['owner_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('owner_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_owner_subscriptions_owner_id'))

    op.drop_table('owner_subscriptions')
    with op.batch_alter_table('ground_staff', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ground_staff_user_id'))
        batch_op.drop_index(batch_op.f('ix_ground_staff_invite_token'))
        batch_op.drop_index(batch_op.f('ix_ground_staff_ground_id'))

    op.drop_table('ground_staff')
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_slug'))

    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
