services:
  cache:
    container_name: "cache"
    image: redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    command:
      - redis-server
      - --requirepass
      - ${REDIS_PASSWORD}
    restart: unless-stopped
    networks:
      - futsalnet

  db:
    container_name: "db"
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: futsaldb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - futsalnet

  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - futsalnet

  apiservice:
    container_name: "apiservice"
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: "."
      DEBUG: "False"
      SECRET_KEY: ${SECRET_KEY}
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: futsaldb
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - uploads_data:/app/media
    depends_on:
      - db
      - cache
    restart: unless-stopped
    networks:
      - futsalnet

  celery-worker:
    container_name: "celery-worker"
    build:
      context: ../backend
      dockerfile: Dockerfile
    command: celery -A src.apps.core.celery_app worker --loglevel=info
    environment:
      PYTHONPATH: "."
      SECRET_KEY: ${SECRET_KEY}

      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: futsaldb

      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

    volumes:
      - uploads_data:/app/media
    depends_on:
      - db
      - cache
    restart: unless-stopped
    networks:
      - futsalnet

  frontend:
    container_name: "frontend"
    build:
      context: ../frontend
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://apiservice:8000}
    ports:
      - "3000:3000"
    depends_on:
      - apiservice
    restart: unless-stopped
    networks:
      - futsalnet

volumes:
  pgdata:
  pgadmin_data:
  uploads_data:

networks:
  futsalnet: